name: Manually triggered deploy workflow

on:
  workflow_dispatch: 

jobs:
  deploy:
    name: "Deploy AWS"
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Configurar AWS CLI
    
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN}}
        aws-region: us-east-1
    
    - name: Copiar plan de AWS
      id: copyfrom
      run: aws s3 cp terraform.tfstate s3://bucket-git-jaime/gitactions/terraform.tfstate 
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_DEFAULT_REGION: ${{ secrets.REGION }}
      continue-on-error: true

    - name: Instalar Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Inicializar Terraform
      run: terraform init

    - name: Aplicar Terraform
      run: terraform apply -auto-approve
